CREATE TABLE Users
	(
	Id INT IDENTITY PRIMARY KEY,
	Username VARCHAR(30) UNIQUE NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Name VARCHAR(50),
	Birthdate DATETIME,
	Age INT CHECK (Age >= 14 AND Age <= 110),
	Email VARCHAR(50) NOT NULL
	)

CREATE TABLE Departments
	(
	Id INT IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
	)

CREATE TABLE Employees
	(
	Id INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(25),
	LastName VARCHAR(25),
	Birthdate DATETIME,
	Age INT CHECK (Age >= 14 AND Age <= 110),
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id)
	)

CREATE TABLE Categories
	(
	Id INT IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id)
	)

CREATE TABLE Status
	(
	Id INT IDENTITY PRIMARY KEY,
	Label VARCHAR(20) NOT NULL
	)

CREATE TABLE Reports
	(
	Id INT IDENTITY PRIMARY KEY,
	CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id),
	StatusId INT NOT NULL FOREIGN KEY REFERENCES Status(Id),
	OpenDate DATETIME NOT NULL,
	CloseDate DATETIME,
	Description VARCHAR(200) NOT NULL,
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	EmployeeId INT FOREIGN KEY REFERENCES Employees(Id) 
	)