CREATE TABLE Passengers
	(
	Id INT IDENTITY PRIMARY KEY,
	FullName VARCHAR(100) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL
	)

CREATE TABLE Pilots
	(
	Id INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(30) UNIQUE NOT NULL,
	LastName VARCHAR(30) UNIQUE NOT NULL,
	Age TINYINT CHECK (AGE >= 21 AND AGE <= 62) NOT NULL,
	Rating FLOAT CHECK (Rating >= 0.0 AND Rating <= 10.0)
	)

CREATE TABLE AircraftTypes
	(
	Id INT IDENTITY PRIMARY KEY,
	TypeName VARCHAR(30) UNIQUE NOT NULL
	)

CREATE TABLE Aircraft
	(
	Id INT IDENTITY PRIMARY KEY,
	Manufacturer VARCHAR(25) NOT NULL,
	Model VARCHAR(30) NOT NULL,
	Year INT NOT NULL,
	FlightHours INT,
	Condition CHAR(1) NOT NULL,
	TypeId INT FOREIGN KEY REFERENCES AircraftTypes(Id) NOT NULL
	)

CREATE TABLE PilotsAircraft
	(
	AircraftId INT FOREIGN KEY REFERENCES Aircraft(Id) NOT NULL,
	PilotId INT FOREIGN KEY REFERENCES Pilots(Id) NOT NULL,
	CONSTRAINT PK_PilotsAircraft PRIMARY KEY (AircraftId,PilotId)
	)

CREATE TABLE Airports
	(
	Id INT IDENTITY PRIMARY KEY,
	AirportName VARCHAR(70) UNIQUE NOT NULL,
	Country VARCHAR(100) UNIQUE NOT NULL,
	)

CREATE TABLE FlightDestinations
	(
	Id INT IDENTITY PRIMARY KEY,
	AirportId INT FOREIGN KEY REFERENCES Airports(Id) NOT NULL,
	Start DATETIME NOT NULL,
	AircraftId INT FOREIGN KEY REFERENCES Aircraft(Id) NOT NULL,
	PassengerId INT FOREIGN KEY REFERENCES Passengers(Id) NOT NULL,
	TicketPrice DECIMAL(16,2) DEFAULT 15 NOT NULL
	)