CREATE TABLE Sizes
	(
	Id INT IDENTITY PRIMARY KEY,
	Length INT NOT NULL CHECK (Length >= 10 AND Length <= 25),
	RingRange DECIMAL(18,4) NOT NULL CHECK (RingRange >= 1.5 AND RingRange <= 7.5)
	)

CREATE TABLE Tastes
	(
	Id INT IDENTITY PRIMARY KEY,
	TasteType VARCHAR(20) NOT NULL,
	TasteStrength VARCHAR(15 ) NOT NULL,
	ImageURL NVARCHAR(100 ) NOT NULL
	)

CREATE TABLE Brands
	(
	Id INT IDENTITY PRIMARY KEY,
	BrandName VARCHAR(30) UNIQUE,
	BrandDescription VARCHAR
	)

CREATE TABLE Cigars
	(
	Id INT IDENTITY PRIMARY KEY,
	CigarName VARCHAR(80) NOT NULL,
	BrandId INT NOT NULL FOREIGN KEY REFERENCES Brands(Id),
	TastId INT NOT NULL FOREIGN KEY REFERENCES Tastes(Id),
	SizeId INT NOT NULL FOREIGN KEY REFERENCES Sizes(Id),
	PriceForSingleCigar DECIMAL(12,2) NOT NULL,
	ImageURL NVARCHAR(100) NOT NULL,
	)

CREATE TABLE Adresses
	(
	Id INT IDENTITY PRIMARY KEY,
	Town VARCHAR(30) NOT NULL,
	Country NVARCHAR(30) NOT NULL,
	Streat NVARCHAR(100) NOT NULL,
	ZIP VARCHAR(20) NOT NULL
	)
	
CREATE TABLE Clients
	(
	Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	Email NVARCHAR(30) NOT NULL,
	AddressId INT NOT NULL FOREIGN KEY REFERENCES Adresses(Id)
	)

CREATE TABLE ClientsCigars
	(
	ClientId INT NOT NULL UNIQUE FOREIGN KEY REFERENCES Clients(Id),
	CigarId INT NOT NULL UNIQUE FOREIGN KEY REFERENCES Cigars(Id),
	CONSTRAINT PK_Clients_Cigars PRIMARY KEY (ClientId, CigarId)
	)